apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-ui-deployment
spec:
  selector:
    matchLabels:
      app: blazor-ui
  template:
    metadata:
      labels:
        app: blazor-ui
    spec:
      containers:
      - name: blazor-ui
        image: music-albums-rating/blazor-ui
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
