version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Microservices/Catalog/Catalog.Api
      dockerfile: Microservices/Catalog/Catalog.Api/Dockerfile
